import { ITableState } from "./interfaces";

export const InitialTableState: ITableState = {
  a1: { piece: "rookWhite", type: "rook", highlighted: false, canBeAttacked: false, color: "white" },
  a2: { piece: "pawnWhite", type: "pawn", highlighted: false, canBeAttacked: false, color: "white" },
  a3: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  a4: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  a5: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  a6: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  a7: { piece: "pawnBlack", type: "pawn", highlighted: false, canBeAttacked: false, color: "black" },
  a8: { piece: "rookBlack", type: "rook", highlighted: false, canBeAttacked: false, color: "black" },
  b1: { piece: "knightWhite", type: "knight", highlighted: false, canBeAttacked: false, color: "white" },
  b2: { piece: "pawnWhite", type: "pawn", highlighted: false, canBeAttacked: false, color: "white" },
  b3: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  b4: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  b5: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  b6: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  b7: { piece: "pawnBlack", type: "pawn", highlighted: false, canBeAttacked: false, color: "black" },
  b8: { piece: "knightBlack", type: "knight", highlighted: false, canBeAttacked: false, color: "black" },
  c1: { piece: "bishopWhite", type: "bishop", highlighted: false, canBeAttacked: false, color: "white" },
  c2: { piece: "pawnWhite", type: "pawn", highlighted: false, canBeAttacked: false, color: "white" },
  c3: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  c4: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  c5: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  c6: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  c7: { piece: "pawnBlack", type: "pawn", highlighted: false, canBeAttacked: false, color: "black" },
  c8: { piece: "bishopBlack", type: "bishop", highlighted: false, canBeAttacked: false, color: "black" },
  d1: { piece: "queenWhite", type: "queen", highlighted: false, canBeAttacked: false, color: "white" },
  d2: { piece: "pawnWhite", type: "pawn", highlighted: false, canBeAttacked: false, color: "white" },
  d3: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  d4: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  d5: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  d6: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  d7: { piece: "pawnBlack", type: "pawn", highlighted: false, canBeAttacked: false, color: "black" },
  d8: { piece: "queenBlack", type: "queen", highlighted: false, canBeAttacked: false, color: "black" },
  e1: { piece: "kingWhite", type: "king", highlighted: false, canBeAttacked: false, color: "white" },
  e2: { piece: "pawnWhite", type: "pawn", highlighted: false, canBeAttacked: false, color: "white" },
  e3: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  e4: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  e5: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  e6: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  e7: { piece: "pawnBlack", type: "pawn", highlighted: false, canBeAttacked: false, color: "black" },
  e8: { piece: "kingBlack", type: "king", highlighted: false, canBeAttacked: false, color: "black" },
  f1: { piece: "bishopWhite", type: "bishop", highlighted: false, canBeAttacked: false, color: "white" },
  f2: { piece: "pawnWhite", type: "pawn", highlighted: false, canBeAttacked: false, color: "white" },
  f3: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  f4: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  f5: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  f6: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  f7: { piece: "pawnBlack", type: "pawn", highlighted: false, canBeAttacked: false, color: "black" },
  f8: { piece: "bishopBlack", type: "bishop", highlighted: false, canBeAttacked: false, color: "black" },
  g1: { piece: "knightWhite", type: "knight", highlighted: false, canBeAttacked: false, color: "white" },
  g2: { piece: "pawnWhite", type: "pawn", highlighted: false, canBeAttacked: false, color: "white" },
  g3: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  g4: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  g5: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  g6: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  g7: { piece: "pawnBlack", type: "pawn", highlighted: false, canBeAttacked: false, color: "black" },
  g8: { piece: "knightBlack", type: "knight", highlighted: false, canBeAttacked: false, color: "black" },
  h1: { piece: "rookWhite", type: "rook", highlighted: false, canBeAttacked: false, color: "white" },
  h2: { piece: "pawnWhite", type: "pawn", highlighted: false, canBeAttacked: false, color: "white" },
  h3: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  h4: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  h5: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  h6: { piece: null, type: null, highlighted: false, canBeAttacked: false, color: null },
  h7: { piece: "pawnBlack", type: "pawn", highlighted: false, canBeAttacked: false, color: "black" },
  h8: { piece: "rookBlack", type: "rook", highlighted: false, canBeAttacked: false, color: "black" },
};
export const FILE_LETTER = ["a", "b", "c", "d", "e", "f", "g", "h"];
export const PAWN_STARTING_POSITIONS = [
  "a2",
  "a7",
  "b2",
  "b7",
  "c2",
  "c7",
  "d2",
  "d7",
  "e2",
  "e7",
  "f2",
  "f7",
  "g2",
  "g7",
  "h2",
  "h7",
];
